- defaults:
    link:
      relink: true
    shell:
      stdout: true
      stdin: true
      stderr: true

- shell:
  - [echo "", Checking dependencies exist, install using local package manager]
  - command -v zsh
  - command -v pip3
  - command -v curl
  - command -v node
  - command -v yarn
  - [command -v solargraph, Run './install-standalone rubyenv' if not found]
